version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: my-mysql-container
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: marble
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
