version: "3.9"

services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password 
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
